# Generated by Django 2.1 on 2019-04-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='lname',
        ),
    ]
