# Generated by Django 2.1 on 2019-04-07 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190406_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Passenger'},
        ),
        migrations.AddField(
            model_name='profile',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Passenger'),
        ),
    ]
