# Generated by Django 2.1.7 on 2019-04-14 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190407_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='Age'),
        ),
    ]
