# Generated by Django 2.1.7 on 2019-04-14 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190414_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Passenger')),
            ],
            options={
                'verbose_name': 'Wallet',
            },
        ),
    ]
