# Generated by Django 2.1.7 on 2019-04-21 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190414_1017'),
        ('bookings', '0002_auto_20190414_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_no', models.CharField(max_length=10, verbose_name='PNR Number')),
                ('seats_booked', models.IntegerField(verbose_name='# of seats booked')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passenger')),
            ],
            options={
                'verbose_name': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField(verbose_name='Train Number')),
                ('train_name', models.CharField(max_length=30, verbose_name='Train Name')),
                ('source', models.CharField(max_length=30, verbose_name='Source')),
                ('destination', models.CharField(max_length=30, verbose_name='Destination')),
                ('seats_remaining', models.IntegerField(verbose_name='# of seats remaining')),
                ('departure_time', models.TimeField(verbose_name='Departure time')),
                ('travel_time', models.DurationField(verbose_name='Travel time')),
            ],
            options={
                'verbose_name': 'Train',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Train'),
        ),
    ]
