# Generated by Django 2.1.7 on 2019-05-02 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='fare',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Fare'),
            preserve_default=False,
        ),
    ]
